// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mim-tool/protobuf/MimMsgProtocal.proto

package cn.sawyer.mim.tool.protobuf.domain;

public final class MsgProtobuf {
  private MsgProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MimMsgProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 srcId = 1;</code>
     * @return Whether the srcId field is set.
     */
    boolean hasSrcId();
    /**
     * <code>required int64 srcId = 1;</code>
     * @return The srcId.
     */
    long getSrcId();

    /**
     * <code>required string srcName = 3;</code>
     * @return Whether the srcName field is set.
     */
    boolean hasSrcName();
    /**
     * <code>required string srcName = 3;</code>
     * @return The srcName.
     */
    java.lang.String getSrcName();
    /**
     * <code>required string srcName = 3;</code>
     * @return The bytes for srcName.
     */
    com.google.protobuf.ByteString
        getSrcNameBytes();

    /**
     * <code>optional int64 destId = 2;</code>
     * @return Whether the destId field is set.
     */
    boolean hasDestId();
    /**
     * <code>optional int64 destId = 2;</code>
     * @return The destId.
     */
    long getDestId();

    /**
     * <code>optional string destName = 4;</code>
     * @return Whether the destName field is set.
     */
    boolean hasDestName();
    /**
     * <code>optional string destName = 4;</code>
     * @return The destName.
     */
    java.lang.String getDestName();
    /**
     * <code>optional string destName = 4;</code>
     * @return The bytes for destName.
     */
    com.google.protobuf.ByteString
        getDestNameBytes();

    /**
     * <code>required string msg = 5;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 5;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 5;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
     * @return The type.
     */
    cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType getType();
  }
  /**
   * Protobuf type {@code cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol}
   */
  public  static final class MimMsgProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol)
      MimMsgProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MimMsgProtocol.newBuilder() to construct.
    private MimMsgProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MimMsgProtocol() {
      srcName_ = "";
      destName_ = "";
      msg_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MimMsgProtocol();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MimMsgProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              srcId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000004;
              destId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              srcName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              destName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msg_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType value = cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                type_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.class, cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.Builder.class);
    }

    /**
     * Protobuf enum {@code cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType)
    }

    private int bitField0_;
    public static final int SRCID_FIELD_NUMBER = 1;
    private long srcId_;
    /**
     * <code>required int64 srcId = 1;</code>
     * @return Whether the srcId field is set.
     */
    public boolean hasSrcId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 srcId = 1;</code>
     * @return The srcId.
     */
    public long getSrcId() {
      return srcId_;
    }

    public static final int SRCNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object srcName_;
    /**
     * <code>required string srcName = 3;</code>
     * @return Whether the srcName field is set.
     */
    public boolean hasSrcName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string srcName = 3;</code>
     * @return The srcName.
     */
    public java.lang.String getSrcName() {
      java.lang.Object ref = srcName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          srcName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string srcName = 3;</code>
     * @return The bytes for srcName.
     */
    public com.google.protobuf.ByteString
        getSrcNameBytes() {
      java.lang.Object ref = srcName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTID_FIELD_NUMBER = 2;
    private long destId_;
    /**
     * <code>optional int64 destId = 2;</code>
     * @return Whether the destId field is set.
     */
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 destId = 2;</code>
     * @return The destId.
     */
    public long getDestId() {
      return destId_;
    }

    public static final int DESTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object destName_;
    /**
     * <code>optional string destName = 4;</code>
     * @return Whether the destName field is set.
     */
    public boolean hasDestName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string destName = 4;</code>
     * @return The destName.
     */
    public java.lang.String getDestName() {
      java.lang.Object ref = destName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destName = 4;</code>
     * @return The bytes for destName.
     */
    public com.google.protobuf.ByteString
        getDestNameBytes() {
      java.lang.Object ref = destName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 5;
    private volatile java.lang.Object msg_;
    /**
     * <code>required string msg = 5;</code>
     * @return Whether the msg field is set.
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string msg = 5;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 5;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
     * @return The type.
     */
    public cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType getType() {
      @SuppressWarnings("deprecation")
      cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType result = cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType.valueOf(type_);
      return result == null ? cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType.MOBILE : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSrcId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSrcName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, srcId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(2, destId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, srcName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destName_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msg_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, srcId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, destId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, srcName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destName_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msg_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol)) {
        return super.equals(obj);
      }
      cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol other = (cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol) obj;

      if (hasSrcId() != other.hasSrcId()) return false;
      if (hasSrcId()) {
        if (getSrcId()
            != other.getSrcId()) return false;
      }
      if (hasSrcName() != other.hasSrcName()) return false;
      if (hasSrcName()) {
        if (!getSrcName()
            .equals(other.getSrcName())) return false;
      }
      if (hasDestId() != other.hasDestId()) return false;
      if (hasDestId()) {
        if (getDestId()
            != other.getDestId()) return false;
      }
      if (hasDestName() != other.hasDestName()) return false;
      if (hasDestName()) {
        if (!getDestName()
            .equals(other.getDestName())) return false;
      }
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSrcId()) {
        hash = (37 * hash) + SRCID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSrcId());
      }
      if (hasSrcName()) {
        hash = (37 * hash) + SRCNAME_FIELD_NUMBER;
        hash = (53 * hash) + getSrcName().hashCode();
      }
      if (hasDestId()) {
        hash = (37 * hash) + DESTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDestId());
      }
      if (hasDestName()) {
        hash = (37 * hash) + DESTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDestName().hashCode();
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol)
        cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.class, cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.Builder.class);
      }

      // Construct using cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        srcId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        srcName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        destId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        destName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_descriptor;
      }

      @java.lang.Override
      public cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol getDefaultInstanceForType() {
        return cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol build() {
        cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol buildPartial() {
        cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol result = new cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.srcId_ = srcId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.srcName_ = srcName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.destId_ = destId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.destName_ = destName_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol) {
          return mergeFrom((cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol other) {
        if (other == cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.getDefaultInstance()) return this;
        if (other.hasSrcId()) {
          setSrcId(other.getSrcId());
        }
        if (other.hasSrcName()) {
          bitField0_ |= 0x00000002;
          srcName_ = other.srcName_;
          onChanged();
        }
        if (other.hasDestId()) {
          setDestId(other.getDestId());
        }
        if (other.hasDestName()) {
          bitField0_ |= 0x00000008;
          destName_ = other.destName_;
          onChanged();
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000010;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSrcId()) {
          return false;
        }
        if (!hasSrcName()) {
          return false;
        }
        if (!hasMsg()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long srcId_ ;
      /**
       * <code>required int64 srcId = 1;</code>
       * @return Whether the srcId field is set.
       */
      public boolean hasSrcId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 srcId = 1;</code>
       * @return The srcId.
       */
      public long getSrcId() {
        return srcId_;
      }
      /**
       * <code>required int64 srcId = 1;</code>
       * @param value The srcId to set.
       * @return This builder for chaining.
       */
      public Builder setSrcId(long value) {
        bitField0_ |= 0x00000001;
        srcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 srcId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        srcId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object srcName_ = "";
      /**
       * <code>required string srcName = 3;</code>
       * @return Whether the srcName field is set.
       */
      public boolean hasSrcName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string srcName = 3;</code>
       * @return The srcName.
       */
      public java.lang.String getSrcName() {
        java.lang.Object ref = srcName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            srcName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string srcName = 3;</code>
       * @return The bytes for srcName.
       */
      public com.google.protobuf.ByteString
          getSrcNameBytes() {
        java.lang.Object ref = srcName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srcName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string srcName = 3;</code>
       * @param value The srcName to set.
       * @return This builder for chaining.
       */
      public Builder setSrcName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        srcName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string srcName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        srcName_ = getDefaultInstance().getSrcName();
        onChanged();
        return this;
      }
      /**
       * <code>required string srcName = 3;</code>
       * @param value The bytes for srcName to set.
       * @return This builder for chaining.
       */
      public Builder setSrcNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        srcName_ = value;
        onChanged();
        return this;
      }

      private long destId_ ;
      /**
       * <code>optional int64 destId = 2;</code>
       * @return Whether the destId field is set.
       */
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 destId = 2;</code>
       * @return The destId.
       */
      public long getDestId() {
        return destId_;
      }
      /**
       * <code>optional int64 destId = 2;</code>
       * @param value The destId to set.
       * @return This builder for chaining.
       */
      public Builder setDestId(long value) {
        bitField0_ |= 0x00000004;
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 destId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object destName_ = "";
      /**
       * <code>optional string destName = 4;</code>
       * @return Whether the destName field is set.
       */
      public boolean hasDestName() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string destName = 4;</code>
       * @return The destName.
       */
      public java.lang.String getDestName() {
        java.lang.Object ref = destName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destName = 4;</code>
       * @return The bytes for destName.
       */
      public com.google.protobuf.ByteString
          getDestNameBytes() {
        java.lang.Object ref = destName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destName = 4;</code>
       * @param value The destName to set.
       * @return This builder for chaining.
       */
      public Builder setDestName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        destName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        destName_ = getDefaultInstance().getDestName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destName = 4;</code>
       * @param value The bytes for destName to set.
       * @return This builder for chaining.
       */
      public Builder setDestNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        destName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 5;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string msg = 5;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 5;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 5;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 5;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
       * @return The type.
       */
      public cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType getType() {
        @SuppressWarnings("deprecation")
        cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType result = cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType.valueOf(type_);
        return result == null ? cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType.MOBILE : result;
      }
      /**
       * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol.MsgType type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol)
    }

    // @@protoc_insertion_point(class_scope:cn.sawyer.mim.tool.protobuf.domain.MimMsgProtocol)
    private static final cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol();
    }

    public static cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MimMsgProtocol>
        PARSER = new com.google.protobuf.AbstractParser<MimMsgProtocol>() {
      @java.lang.Override
      public MimMsgProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MimMsgProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MimMsgProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MimMsgProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.sawyer.mim.tool.protobuf.domain.MsgProtobuf.MimMsgProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&mim-tool/protobuf/MimMsgProtocal.proto" +
      "\022\"cn.sawyer.mim.tool.protobuf.domain\"\324\001\n" +
      "\016MimMsgProtocol\022\r\n\005srcId\030\001 \002(\003\022\017\n\007srcNam" +
      "e\030\003 \002(\t\022\016\n\006destId\030\002 \001(\003\022\020\n\010destName\030\004 \001(" +
      "\t\022\013\n\003msg\030\005 \002(\t\022H\n\004type\030\006 \002(\0162:.cn.sawyer" +
      ".mim.tool.protobuf.domain.MimMsgProtocol" +
      ".MsgType\")\n\007MsgType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020" +
      "\001\022\010\n\004WORK\020\002B1\n\"cn.sawyer.mim.tool.protob" +
      "uf.domainB\013MsgProtobuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_sawyer_mim_tool_protobuf_domain_MimMsgProtocol_descriptor,
        new java.lang.String[] { "SrcId", "SrcName", "DestId", "DestName", "Msg", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
